config/routes.rb
Musicapp::Application.routes.draw do
  root to: 'bands#index'

  resources :users do
    get 'activate', on: :collection
  end

  resource :session

  resources :bands do
    resources :albums, only: [:index, :new, :create]
  end

  resources :albums, except: [:index, :new, :create] do
    resources :songs, only: [:index, :new, :create]
  end

  resources :songs, except: [:index, :new, :create] do
    resources :notes, only: [:create]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  email            :string(255)      not null
#  password_digest  :string(255)      not null
#  session_token    :string(255)      not null
#  created_at       :datetime
#  updated_at       :datetime
#  activated        :boolean          default(FALSE)
#  activation_token :string(255)
#

class User < ActiveRecord::Base
  attr_reader :password

  before_validation :ensure_session_token
  before_validation :ensure_activation_token

  validates :password_digest, :presence => true
  validates :password, :presence => true, :on => :create
  validates :password, :length => { :minimum => 6, :allow_nil => true }
  validates :session_token, :activation_token, :presence => true, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def activate!
    self.activated = true
    self.save!
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def password=(pt)
    @password = pt
    self.password_digest = BCrypt::Password.create(pt)
  end

  def is_password?(pt)
    BCrypt::Password.new(self.password_digest).is_password?(pt)
  end

  def self.find_by_credentials(params)
    user = User.find_by(:email => params[:email])
    user.try(:is_password?, params[:password]) ? user : nil
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def ensure_activation_token
    self.activation_token ||= self.class.generate_session_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.activation_email(@user).deliver!
      redirect_to bands_url
    else
      flash.now[:error] = @user.errors.full_messages
      render :new
    end
  end

  def activate
    @user = User.find_by(activation_token: params[:activation_token])
    if @user
      @user.activate!
      login!
      redirect_to '/'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/activate.html.erb
<form action="<%= song_notes_url(song_id) %>" method="post"	enctype="multipart/form-data">
	<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

	<input type="hidden" name="note[song_id]" value="<%= song_id %>">
	<input type="hidden" name="note[user_id]" value="<%= user_id %>">

	<input type="submit" value="Activate">
</form>

app/views/users/new.html.erb
<h1>Register Here</h1>
<form action="<%= users_url %>" method="post">
	<input
	name="authenticity_token"
	type="hidden"
	value="<%= form_authenticity_token %>">
	<label for="user_name">Email Address</label>
	<input name="user[email]" id="user_name" type"text">
	<br>

	<label for="password">Password</label>
	<input name="user[password]" id="password" type="password">
	<br>
	<input type="submit" value="Sign Up!!!">
</form>