config/routes.rb
Musicapp::Application.routes.draw do
  root to: 'bands#index'

  resources :users do
    get 'activate', on: :collection
  end

  resource :session

  resources :bands do
    resources :albums, only: [:index, :new, :create]
  end

  resources :albums, except: [:index, :new, :create] do
    resources :songs, only: [:index, :new, :create]
  end

  resources :songs, except: [:index, :new, :create] do
    resources :notes, only: [:create]
  end
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  album_name :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Album < ActiveRecord::Base
  validates :band_id, :album_name, presence: true

  belongs_to :band

  has_many :songs, dependent: :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :get_album, only: [:destroy, :show, :edit, :update]

  def index
    @albums = Album.where(band_id: params[:band_id])
  end

  def show
  end

  def new
    get_band
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to band_albums_url
    else
      flash.now[:error] = ["Invalid Band Credentials"]
      render :new
    end
  end

  def edit
  end

  def update
    if @album.update_attributes(album_params)
      redirect_to band_albums_url
    else
      flash.now[:error] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album.destroy!
    redirect_to bands_url
  end

  private

  def get_band
    @band = Band.find(params[:band_id])
  end

  def get_album
    @album = Album.find(params[:id])
  end

  def album_params
    params.require(:album).permit(:album_name, :band_id)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<form action="<%= album.persisted? ? album_url(album) : band_albums_url %>" 	method="post"	enctype="multipart/form-data">
	<% if album.persisted? %>
		<input type='hidden' name="_method" value="PATCH">
	<% end %>

	<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

	<label for="album_name">Album Name</label>
	<input type="text" name="album[album_name]" value="<%= album.album_name %>" id="album_name">
	<br>
	<label for="band">Band</label>
			<br>
	<select name="album[band_id]" id="band">
		<% Band.all.order(:name).each do |band| %>
			<% if band == album.band %>
				<option value="<%= band.id %>" selected><%= band.name %></option>
			<% else %>
				<option value="<%= band.id %>"><%= band.name %></option>
			<% end %>
		<% end %>
	</select>
	<br>

	<input type="submit" value="Create Album">
</form>

app/views/albums/edit.html.erb
<%= render 'form', :album => @album %>

app/views/albums/index.html.erb
<% @albums.each do |album| %>
	<%= link_to album.album_name, album_url(album) %>
	<br>
<% end %>
<br>

app/views/albums/new.html.erb
<%= render 'form', :album => @album, album_band: @band %>

app/views/albums/show.html.erb
<%= @album.album_name %>
<br>
<%= link_to @album.band.name, band_url(@album.band) %>
<br>
<% @album.songs.each do |song| %>
	<%= link_to song.title, song_url(song) %>
	<br>
<% end %>
<%= link_to "Add New Song", new_album_song_url(@album) %>
<%= button_to "Destroy Album", album_url(@album), method: 'delete' %>