config/routes.rb
Musicapp::Application.routes.draw do
  root to: 'bands#index'

  resources :users do
    get 'activate', on: :collection
  end

  resource :session

  resources :bands do
    resources :albums, only: [:index, :new, :create]
  end

  resources :albums, except: [:index, :new, :create] do
    resources :songs, only: [:index, :new, :create]
  end

  resources :songs, except: [:index, :new, :create] do
    resources :notes, only: [:create]
  end
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime
#  updated_at :datetime
#

class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums, dependent: :destroy

  has_many :songs, through: :albums
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :get_band, only: [:destroy, :show, :edit, :update]

  def index
    @bands = Band.all
  end

  def show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to bands_url
    else
      flash.now[:error] = ["Invalid Band Credentials"]
      render :new
    end
  end

  def edit
    render :edit
  end

  def update
    if @band.update_attributes(band_params)
      redirect_to bands_url
    else
      flash.now[:error] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band.destroy!
  end

  private

  def get_band
    @band = Band.find(params[:id])
  end

  def band_params
    params.require(:band).permit(:name)
  end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<form action="<%= band.persisted? ? band_url(band) : bands_url %>" 	       	   	method="post"	enctype="multipart/form-data">
	<% if band.persisted? %>
		<input type='hidden' name="_method" value="PATCH">
	<% end %>
	<input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

	<label for="band_name">Name</label>
	<input type="text" name="band[name]" value="<%= band.name %>" id="band_name">
	<br>
	<input type="submit" value="Create Band">
</form>

app/views/bands/edit.html.erb
<%= render 'form', :band => @band %>

app/views/bands/index.html.erb
<% Band.all.order(:name).each do |band| %>
	<%= link_to band.name, band_url(band) %>
	<br>
<% end %>

<%= link_to "Add a New Band", new_band_url %>

app/views/bands/new.html.erb
<%= render 'form', :band => @band %>

app/views/bands/show.html.erb
<table>
	<tr>
		<td>Name: </td>
		<td><%= @band.name %></td>
	</tr>
</table>
<% @band.albums.each do |album| %>
	<%= link_to album.album_name, album_url(album.id) %>
	<br>
	<% @band.songs.each do |song| %>
		<%= link_to song.title, song_url(song) %>
		<br>
	<% end %>
	<br>
<% end %>
<br>
<%= link_to "Add New Album", new_band_album_url(@band.id) %>