config/routes.rb
Musicapp::Application.routes.draw do
  root to: 'bands#index'

  resources :users do
    get 'activate', on: :collection
  end

  resource :session

  resources :bands do
    resources :albums, only: [:index, :new, :create]
  end

  resources :albums, except: [:index, :new, :create] do
    resources :songs, only: [:index, :new, :create]
  end

  resources :songs, except: [:index, :new, :create] do
    resources :notes, only: [:create]
  end
end

app/views/layouts/_header.html.erb
<% if logged_in? %>
<h1> Welcome to Music Inventory! </h1>
<div class="right">
	<div class="button">
		<%= button_to "Log Out", session_url, method: 'delete' %>
	</div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Musicapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <style>
   .td-style{
     padding: 5px;
   }

	 .right {
		 float: right;
	 }

   #requests-style{
     padding: 10px;
     border: 2px solid #ccc;

   }

   body{
     font-family: verdana;
     color: black;
     font-weight: bold;
     background-image: url('http://www.hollywoodreporter.com/sites/default/files/2013/08/florida_georgia_line.jpg');
   }

   #outer-container {
   width: 100%;
   opacity: 0.8;
   filter: alpha(opacity=80);
   }

   #inner-container{
     width: 60%;
     margin: 20px auto;
     border: 2px solid #ccc;
     border-radius: 5px;
     padding: 10px;
     background: white;
   }
   </style>
 </head>
 <body>
   <div id="outer-container">
     <div id="inner-container">
			 <%= render 'layouts/header' %>
 			<% if flash[:error] %>
 				<% flash[:error].each do |error| %>
 					<ul style="color:red;"><%= error %></ul>
 				<% end %>
 			<% end %>
       <%= yield %>
     </div>
   </div>
</body>
</html>